"""initial

Revision ID: 476939c77bf1
Revises: 
Create Date: 2026-05-07 23:12:51.565210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '476939c77bf1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exchange', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candles_exchange'), 'candles', ['exchange'], unique=False)
    op.create_index(op.f('ix_candles_symbol'), 'candles', ['symbol'], unique=False)
    op.create_index(op.f('ix_candles_timestamp'), 'candles', ['timestamp'], unique=False)
    op.create_table('open_interest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exchange', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_open_interest_exchange'), 'open_interest', ['exchange'], unique=False)
    op.create_index(op.f('ix_open_interest_symbol'), 'open_interest', ['symbol'], unique=False)
    op.create_index(op.f('ix_open_interest_timestamp'), 'open_interest', ['timestamp'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('setup_type', sa.String(length=64), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_symbol'), 'signals', ['symbol'], unique=False)
    op.create_index(op.f('ix_signals_timestamp'), 'signals', ['timestamp'], unique=False)
    op.create_table('tickers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exchange', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('bid', sa.Float(), nullable=True),
    sa.Column('ask', sa.Float(), nullable=True),
    sa.Column('last', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('change_pct', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickers_exchange'), 'tickers', ['exchange'], unique=False)
    op.create_index(op.f('ix_tickers_symbol'), 'tickers', ['symbol'], unique=False)
    op.create_index(op.f('ix_tickers_timestamp'), 'tickers', ['timestamp'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('entry_time', sa.DateTime(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('exit_time', sa.DateTime(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_symbol'), 'trades', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_symbol'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_tickers_timestamp'), table_name='tickers')
    op.drop_index(op.f('ix_tickers_symbol'), table_name='tickers')
    op.drop_index(op.f('ix_tickers_exchange'), table_name='tickers')
    op.drop_table('tickers')
    op.drop_index(op.f('ix_signals_timestamp'), table_name='signals')
    op.drop_index(op.f('ix_signals_symbol'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_open_interest_timestamp'), table_name='open_interest')
    op.drop_index(op.f('ix_open_interest_symbol'), table_name='open_interest')
    op.drop_index(op.f('ix_open_interest_exchange'), table_name='open_interest')
    op.drop_table('open_interest')
    op.drop_index(op.f('ix_candles_timestamp'), table_name='candles')
    op.drop_index(op.f('ix_candles_symbol'), table_name='candles')
    op.drop_index(op.f('ix_candles_exchange'), table_name='candles')
    op.drop_table('candles')
    # ### end Alembic commands ###
